// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "dev-playground",
    columns: [
      { name: "user_email", type: "email" },
      { name: "user_id", type: "string" },
      { name: "transcription", type: "text" },
      { name: "youtube_url", type: "string" },
      { name: "Info", type: "string" },
      { name: "video_title", type: "string" },
    ],
  },
  {
    name: "Dashboard",
    columns: [
      { name: "user_id", type: "string" },
      { name: "video_name", type: "string" },
      { name: "title", type: "string" },
      { name: "thumbnail", type: "text" },
      { name: "author", type: "string" },
      { name: "url", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type DevPlayground = InferredTypes["dev-playground"];
export type DevPlaygroundRecord = DevPlayground & XataRecord;

export type Dashboard = InferredTypes["Dashboard"];
export type DashboardRecord = Dashboard & XataRecord;

export type DatabaseSchema = {
  "dev-playground": DevPlaygroundRecord;
  Dashboard: DashboardRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://satish-s-workspace-6midd6.us-east-1.xata.sh/db/Nyalaan",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
